basePath: /
host: localhost:4005
info:
  contact: {}
  description: API Server for VK-REST-API Application
  title: VK-REST-API API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
